name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Check for updates
      run: |
        npm outdated || true
        echo "Checking for security vulnerabilities..."
        npm audit || true

    - name: Update dependencies
      run: |
        npm update
        npm audit fix || true

    - name: Test after updates
      run: |
        npm ci
        npm run lint
        npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes:
          - Updated npm dependencies to latest compatible versions
          - Applied security fixes where available
          
          ### Testing:
          - ✅ ESLint passes
          - ✅ TypeScript compilation successful
          - ✅ Build completes successfully
          
          Please review the changes and merge if everything looks good.
        branch: automated-dependency-updates
        delete-branch: true